"""
Exporter — экспорт golden path в готовые артефакты.
Форматы: Markdown runbook, GitHub Issue, Bash script, Makefile.
"""

from datetime import datetime


def to_markdown(golden_path_text: str, title: str = "Runbook") -> str:
    """Golden path → Markdown runbook."""
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"""# {title}

> Сгенерировано: {now}

{golden_path_text}

---
*Agentic RAG — автоматически извлечённый golden path*
"""


def to_github_issue(golden_path_text: str, title: str = "Implementation Plan") -> str:
    """Golden path → GitHub Issue body."""
    return f"""## {title}

{golden_path_text}

---
<sub>Auto-generated by Agentic RAG</sub>
"""


def to_bash_script(steps: list[dict], title: str = "setup") -> str:
    """Успешные шаги → bash-скрипт (только команды из action)."""
    lines = [
        "#!/usr/bin/env bash",
        f"# {title}",
        f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        "set -euo pipefail",
        "",
    ]
    for s in steps:
        if s["status"] != "success":
            continue
        action = s["action"]
        # Попробуем вытащить команду, если action выглядит как "описание: команда"
        if ":" in action:
            parts = action.split(":", 1)
            cmd_part = parts[1].strip()
            lines.append(f"# {parts[0].strip()}")
            lines.append(cmd_part)
        else:
            lines.append(f"# {action}")
            lines.append(f"echo 'TODO: {action}'")
        lines.append("")
    lines.append('echo "Done!"')
    return "\n".join(lines)


def to_makefile(steps: list[dict]) -> str:
    """Успешные шаги → Makefile targets."""
    lines = [
        f"# Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        ".PHONY: all",
        "",
    ]
    targets = []
    for i, s in enumerate(steps):
        if s["status"] != "success":
            continue
        name = s.get("tags", ["step"])[0] if s.get("tags") else f"step{i+1}"
        if name in targets:
            name = f"{name}_{i+1}"
        targets.append(name)
        if ":" in s["action"]:
            cmd = s["action"].split(":", 1)[1].strip()
        else:
            cmd = f"@echo 'TODO: {s['action']}'"
        lines.append(f"{name}:")
        lines.append(f"\t{cmd}")
        lines.append("")

    lines.insert(2, f"all: {' '.join(targets)}")
    return "\n".join(lines)


def to_checklist(steps: list[dict]) -> str:
    """Все шаги → markdown checklist."""
    lines = ["## Checklist\n"]
    for s in steps:
        check = "x" if s["status"] == "success" else " "
        icon = {"success": "done", "error": "FAILED", "rollback": "rolled back", "partial": "partial"}.get(s["status"], "")
        lines.append(f"- [{check}] {s['action']} — {s['result']} `{icon}`")
    return "\n".join(lines)


def save(content: str, filename: str) -> str:
    """Сохранить в файл и вернуть путь."""
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)
    return filename
